Geometrikunst 2
kodeklubben/oppgaver pull request #1577
Opened 2022-02-28 14:35 UTC by camyrland

enda en test

2022-02-28 17:03 UTC, tjesi requested changes
en håndfull med småpirk, men burde være enkelt å endre slik at vi kan få den publisert snarest

2022-02-28 17:03 UTC, tjesi commented on src/scratch/geometrikunst/README.md
> +Her må elevene bygge om koden fra steg 2 til å bli slik.
"... til å bli som følger."

2022-02-28 17:03 UTC, tjesi commented on src/scratch/geometrikunst/README.md
> +For figuren `Pencil`
kolon

2022-02-28 17:03 UTC, tjesi commented on src/scratch/geometrikunst/README.md
> +For figuren `Button1`
kolon

2022-02-28 17:03 UTC, tjesi commented on src/scratch/geometrikunst/README.md
> +For figuren `Pencil`
kolon

2022-02-28 17:03 UTC, tjesi commented on src/scratch/geometrikunst/README.md
> +For figuren `Pencil`
kolon

2022-03-01 08:48 UTC, camyrland commented on src/scratch/geometrikunst/geometrikunst.md
> +360 : 4 = 90
Er det divisjonseksemplene du mener? Hele denne delen ser ok ut i editoren.
![divisjon](https://user-images.githubusercontent.com/64355803/156135861-8b9f2152-f253-45cd-a545-ba880d311358.png)

2022-03-01 09:21 UTC, tjesi commented on src/scratch/geometrikunst/geometrikunst.md
> +360 : 4 = 90
ja. rart. når eg bygger den i nettleseren så kommer alt på en linje. det virker å være en forskjell her mellom editoren og byggeren.... tror saken løses ved å sette inn et ekstra linjeskift mellom ligningene.

2022-03-08 18:05 UTC, merged